// @name GetAll
GET http://localhost:3000/people

###

// @name GetSiriusFailure
GET http://localhost:3000/people/Sirius

###
// @name CreateSirius
POST http://localhost:3000/people/
Content-Type: application/json

{
    "name":"Sirius"
}

###
// @name GetAllWithSirius
GET http://localhost:3000/people

###
// @name GetSirius
GET http://localhost:3000/people/Sirius

###
// @name RemoveSirius
DELETE http://localhost:3000/people/Sirius

###
// @name UpdateSirius
PUT http://localhost:3000/people/Sirius
Content-Type: application/json

{
  "name": "Sirius",
  "id": "Sirius",
  "type": "Major",
  "skills": {
    "Battle": {
      "name": "Battle",
      "id": "Battle",
      "minValue": 4,
      "maxValue": 8,
      "current": 4
    },
    "Communicate": {
      "name": "Communicate",
      "id": "Communicate",
      "minValue": 4,
      "maxValue": 8,
      "current": 4
    },
    "Duty": {
      "name": "Duty",
      "id": "Duty",
      "minValue": 4,
      "maxValue": 8,
      "current": 4
    },
    "Move": {
      "name": "Move",
      "id": "Move",
      "minValue": 4,
      "maxValue": 8,
      "current": 6
    },
    "Understand": {
      "name": "Understand",
      "id": "Understand",
      "minValue": 4,
      "maxValue": 8,
      "current": 4
    }
  }
}